### ISSUE TITLE
Setup an automatic locale build of the overall api (and next into a distant repository)

### ISSUE THREAD

**Issue by chapuisk** [ANRGenstar/genstar#15]

**Comment by reyman** [comment]
Ok, first version works on my computer :) 

- `mvn clean install` compile and build the different jar with correct manifest for OSGI. 
- `mvn deploy` upload the jar on bintray, but you need an account with credentials to do that.

**Comment by chapuisk** [comment]
I've tested it too and work perfectly with template project; i.e. the exemple developed in template project works fine with the remote build of the genstar library
