### ISSUE TITLE
create a framateam 

### ISSUE THREAD

**Issue by samthiriot** [ANRGenstar/genstar#2]

**Comment by reyman** [comment]
Alors c'est comme vous le sentez, mais je peux aussi créer ça sur un VPS dont je m'occupe, avec du docker tout ça.

**Comment by samthiriot** [comment]
J'imagine que si tu es prêt à prendre la charge de l'administration de tout ça, personne ne t'en voudra ?

**Comment by reyman** [comment]
Noramelement vous avez reçu une invitation pour vous connecter à team.comnmodel.org qui possède un chan gospl.
