### ISSUE TITLE
make GosplInputDataManager use the Dictionnary type

### ISSUE THREAD

**Issue by samthiriot** [ANRGenstar/genstar#47]
except if there is a good reason not to do it - what do you think @chapuisk  ?

**Comment by chapuisk** [comment]
`GosplInputDataManager` decodes input data based on a broader scope configuration file -- `GenstarConfigurationFile` which can have many dictionary and also information about how to parse data file.

**Comment by chapuisk** [comment]
Did it answer you concerned @samthiriot ? If it did, i let you close the issue ... if not, can you explicit how you expect `GosplInputDataManager` to use dictionaries ?

**Comment by samthiriot** [comment]
I started already, pull first !

**Comment by chapuisk** [comment]
Ok great ! I stated to work on it and saw one failure in the process: Recorded attribute are not recognize (I open an issue for this).

**Comment by chapuisk** [comment]
From my point of view `GosplInputDataManager` now only work on attribute based on ones provided by dictionaries

PS: dictionary takes only one 'n' in english
