### ISSUE TITLE
LocalisePopulation() going wrong with localizationInNestWithNumbers()

### ISSUE THREAD

**Issue by RemakeTm** [ANRGenstar/genstar#78]
When trying to localise a specific population using localizationInNestWithNumbers() (from SPLocalizer.localisePopulation()), all SpllEntity.location from the population are set to null, and hence, get deleted by SPLocalizer line 155 `outputPopulation.removeIf(a -> a.getLocation() == null);`, resulting in bugs afterward when trying to access their location.

I get this bug when trying to launch rouen.spll.LocalisationRouenIJGIS_3 and / or rouen.spll.LocalisationRouenIJGIS_4 from the template repository using the java_11_migration branch of genstar.

[BugFilesTemplate.zip](https://github.com/ANRGenstar/genstar/files/6884073/BugFilesTemplate.zip)

**Comment by ptaillandier** [comment]
It is normally fixed. @RemakeTm : could you test it (and close the issue if it is working).

**Comment by RemakeTm** [comment]
It is indeed fixed, thanks a lot ! In the end what was the problem ?

**Comment by ptaillandier** [comment]
Something linked to the way of managing spatial constraints
